[theme]
base="light"
primaryColor="#f08013"            # Heliconia, usado en botones y acentos
backgroundColor="#ffffff"         # Fondo blanco institucional
secondaryBackgroundColor="#008776" # Eucalipto, usado en paneles
textColor="#404827"               # Roble, para títulos y textos principales

[client]
toolbarMode = "minimal"
