[theme]
base="light"
primaryColor="#f08013"            # Heliconia, para botones y acentos
backgroundColor="#ffffff"         # Fondo blanco institucional
secondaryBackgroundColor="#81bb26" # Acacia, usado en paneles y sidebar
textColor="#404827"               # Roble, para títulos y texto principal

[client]
toolbarMode = "minimal"
